"use client"

import { createContext, useContext, useState, useEffect, type ReactNode } from "react"

type LanguageContextType = {
  language: "ru" | "en"
  setLanguage: (language: "ru" | "en") => void
  t: (key: string) => string
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined)

// Словарь переводов
const translations: Record<string, Record<string, string>> = {
  ru: {
    // Навигация
    "nav.home": "Главная",
    "nav.tickets": "Заявки",
    "nav.myTickets": "Мои запросы",
    "nav.knowledgeBase": "База знаний",
    "nav.users": "Пользователи",
    "nav.analytics": "Аналитика",
    "nav.logout": "Выйти",

    // Главная страница
    "home.greeting.morning": "Доброе утро",
    "home.greeting.afternoon": "Добрый день",
    "home.greeting.evening": "Добрый вечер",
    "home.welcome": "Добро пожаловать в систему технической поддержки",
    "home.myRequests": "Мои запросы",
    "home.inProgress": "В работе",
    "home.resolved": "Решено",
    "home.averageTime": "Среднее время",
    "home.myTickets": "Мои заявки",
    "home.newTickets": "Новые заявки",
    "home.resolvedToday": "Решено сегодня",
    "home.totalTickets": "Всего заявок",
    "home.totalUsers": "Пользователи",
    "home.kbArticles": "Статьи БЗ",
    "home.activeTickets": "Активные заявки",
    "home.quickActions": "Быстрые действия",
    "home.recentUpdates": "Последние обновления",
    "home.createTicket": "Создать заявку",
    "home.createTicketDesc": "Сообщить о проблеме или запросить помощь",
    "home.myTicketsDesc": "Просмотреть статус ваших заявок",
    "home.knowledgeBaseDesc": "Найти ответы на частые вопросы",
    "home.manageTickets": "Управление заявками",
    "home.manageTicketsDesc": "Просмотреть и обработать заявки",
    "home.manageKB": "База знаний",
    "home.manageKBDesc": "Просмотреть и редактировать статьи",
    "home.createArticle": "Создать статью",
    "home.createArticleDesc": "Добавить новую статью в БЗ",
    "home.manageUsers": "Управление пользователями",
    "home.manageUsersDesc": "Управление учетными записями",
    "home.analyticsDesc": "Просмотреть отчеты и статистику",
    "home.systemUpdated": "Система обновлена",
    "home.systemUpdatedDesc": "Добавлены новые функции управления заявками",
    "home.kbUpdated": "База знаний пополнена",
    "home.kbUpdatedDesc": "Добавлены новые статьи по безопасности",
    "home.maintenance": "Плановое обслуживание",
    "home.maintenanceDesc": "Запланировано на выходные",

    // Заявки
    "tickets.title": "Управление заявками",
    "tickets.subtitle": "Обработка и назначение заявок на техническую поддержку",
    "tickets.createTicket": "Создать заявку",
    "tickets.searchPlaceholder": "Поиск заявок...",
    "tickets.sortNewest": "Сначала новые",
    "tickets.sortOldest": "Сначала старые",
    "tickets.sortPriority": "По приоритету",
    "tickets.sortStatus": "По статусу",
    "tickets.allTickets": "Все",
    "tickets.openTickets": "Открытые",
    "tickets.inProgressTickets": "В работе",
    "tickets.resolvedTickets": "Решенные",
    "tickets.closedTickets": "Закрытые",
    "tickets.assignedTo": "Назначено:",
    "tickets.noTickets": "Заявки не найдены по заданным критериям.",
    "tickets.takeTicket": "Взять в работу",
    "tickets.newTicketTitle": "Создать новую заявку",
    "tickets.newTicketSubtitle": "Опишите вашу проблему или запрос",
    "tickets.backToTickets": "Назад к заявкам",
    "tickets.ticketInfo": "Информация о заявке",
    "tickets.ticketTitle": "Заголовок заявки",
    "tickets.ticketTitlePlaceholder": "Кратко опишите проблему",
    "tickets.description": "Описание проблемы",
    "tickets.descriptionPlaceholder": "Подробно опишите проблему, шаги для воспроизведения, ожидаемый результат",
    "tickets.category": "Категория",
    "tickets.selectCategory": "Выберите категорию",
    "tickets.priority": "Приоритет",
    "tickets.contactInfo": "Контактная информация",
    "tickets.name": "Имя",
    "tickets.email": "Email",
    "tickets.phone": "Телефон",
    "tickets.creating": "Создание...",

    // Категории заявок
    "category.technical": "Техническая поддержка",
    "category.account": "Проблемы с аккаунтом",
    "category.billing": "Вопросы по оплате",
    "category.feature": "Запрос функции",
    "category.other": "Другое",

    // База знаний
    "kb.title": "База знаний",
    "kb.subtitle": "Найдите ответы на часто задаваемые вопросы и инструкции",
    "kb.createArticle": "Создать статью",
    "kb.searchPlaceholder": "Поиск по базе знаний...",
    "kb.allCategories": "Все категории",
    "kb.sortNewest": "Сначала новые",
    "kb.sortOldest": "Сначала старые",
    "kb.sortMostViewed": "По просмотрам",
    "kb.sortMostHelpful": "По полезности",
    "kb.views": "просмотров",
    "kb.author": "Автор:",
    "kb.readArticle": "Читать статью",
    "kb.noArticles": "Статьи не найдены по вашему запросу.",
    "kb.editorTitle": "Редактор базы знаний",
    "kb.backToKB": "Назад к базе знаний",
    "kb.saveDraft": "Сохранить черновик",
    "kb.publish": "Опубликовать",
    "kb.publishing": "Публикация...",
    "kb.editing": "Редактирование",
    "kb.preview": "Предпросмотр",
    "kb.articleTitle": "Заголовок статьи",
    "kb.articleTitlePlaceholder": "Введите заголовок статьи",
    "kb.formatPanel": "Панель форматирования",
    "kb.content": "Содержание статьи",
    "kb.contentPlaceholder": "Введите содержание статьи (поддерживается Markdown)",
    "kb.markdownSupport": "Поддерживается Markdown:",
    "kb.bold": "Жирный",
    "kb.italic": "Курсив",
    "kb.heading": "Заголовок",
    "kb.link": "Ссылка",
    "kb.code": "Код",
    "kb.list": "Список",
    "kb.selectCategory": "Выберите категорию",
    "kb.tags": "Теги",
    "kb.publishSettings": "Настройки публикации",
    "kb.recommended": "Рекомендуемая статья",
    "kb.allowComments": "Разрешить комментарии",
    "kb.articlePublished": "Статья успешно опубликована!",
    "kb.articlePublishedDesc": "была успешно добавлена в базу знаний.",
    "kb.toKnowledgeBase": "К базе знаний",
    "kb.createAnother": "Создать еще",

    // Аналитика
    "analytics.title": "Расширенная аналитика",
    "analytics.subtitle": "Детальные отчеты и статистика по работе службы поддержки",
    "analytics.last7days": "Последние 7 дней",
    "analytics.last30days": "Последние 30 дней",
    "analytics.last90days": "Последний год",
    "analytics.exportExcel": "Экспорт Excel",
    "analytics.exporting": "Экспорт...",
    "analytics.print": "Печать",
    "analytics.totalTickets": "Всего запросов",
    "analytics.activeUsers": "Активные пользователи",
    "analytics.avgResolutionTime": "Среднее время решения",
    "analytics.teamEfficiency": "Эффективность команды",
    "analytics.requiresAttention": "Требуется внимание",
    "analytics.usersAwaitingApproval": "пользователей ожидают одобрения регистрации",
    "analytics.goToManagement": "Перейти к управлению",
    "analytics.activityDynamics": "Динамика заявок (последние 7 дней)",
    "analytics.created": "Создано:",
    "analytics.resolved": "Решено:",
    "analytics.statusDistribution": "Распределение по статусам",
    "analytics.popularCategories": "Популярные категории",
    "analytics.priorityDistribution": "Распределение по приоритетам",
    "analytics.recentActivity": "Последняя активность",
    "analytics.teamEfficiencyTable": "Эффективность команды поддержки",
    "analytics.employee": "Сотрудник",
    "analytics.assigned": "Назначено",
    "analytics.resolved": "Решено",
    "analytics.efficiency": "Эффективность",
    "analytics.avgTime": "Среднее время",
    "analytics.kbStats": "Статистика базы знаний",
    "analytics.publishedArticles": "Опубликованных статей",
    "analytics.totalViews": "Всего просмотров",
    "analytics.helpfulRatings": "Полезных оценок",
    "analytics.helpfulnessRating": "Рейтинг полезности",

    // Общие
    "common.loading": "Загрузка...",
    "common.save": "Сохранить",
    "common.cancel": "Отмена",
    "common.delete": "Удалить",
    "common.edit": "Редактировать",
    "common.create": "Создать",
    "common.search": "Поиск",
    "common.filter": "Фильтр",
    "common.all": "Все",
    "common.active": "Активные",
    "common.inactive": "Неактивные",
    "common.yes": "Да",
    "common.no": "Нет",
    "common.back": "Назад",
    "common.next": "Далее",
    "common.submit": "Отправить",
    "common.close": "Закрыть",

    // Роли
    "role.admin": "Администратор",
    "role.support": "Сотрудник поддержки",
    "role.client": "Клиент",

    // Статусы заявок
    "status.new": "Открыта",
    "status.in-progress": "В работе",
    "status.resolved": "Решена",
    "status.closed": "Закрыта",

    // Приоритеты
    "priority.low": "Низкий",
    "priority.medium": "Средний",
    "priority.high": "Высокий",
    "priority.urgent": "Критический",

    // Авторизация
    "auth.login": "Вход",
    "auth.register": "Регистрация",
    "auth.email": "Email",
    "auth.password": "Пароль",
    "auth.confirmPassword": "Подтвердите пароль",
    "auth.firstName": "Имя",
    "auth.lastName": "Фамилия",
    "auth.loginButton": "Войти",
    "auth.registerButton": "Зарегистрироваться",
    "auth.switchToRegister": "Нет аккаунта? Зарегистрируйтесь",
    "auth.switchToLogin": "Уже есть аккаунт? Войдите",

    // Уведомления
    "notifications.title": "Уведомления",
    "notifications.markAsRead": "Отметить как прочитанное",
    "notifications.markAllAsRead": "Отметить все как прочитанные",
    "notifications.noNotifications": "Нет уведомлений",
    "notifications.newTicket": "Создана новая заявка",
    "notifications.ticketAssigned": "Заявка назначена вам",
    "notifications.ticketUpdated": "Заявка обновлена",
    "notifications.ticketResolved": "Заявка решена",

    // Время
    "time.hoursAgo": "часа назад",
    "time.daysAgo": "дня назад",
    "time.today": "сегодня",
    "time.yesterday": "вчера",

    // Авторизация (login)
    "login.title": "Вход в систему",
    "login.subtitle": "Войдите в свою учетную запись",
    "login.systemDescription": "Система технической поддержки",
    "login.email": "Email",
    "login.password": "Пароль",
    "login.emailPlaceholder": "Введите ваш email",
    "login.passwordPlaceholder": "Введите ваш пароль",
    "login.login": "Войти",
    "login.loggingIn": "Вход...",
    "login.testAccounts": "Тестовые аккаунты",
    "login.noAccount": "Нет аккаунта?",
    "login.register": "Зарегистрироваться",
    "login.invalidCredentials": "Неверные учетные данные",

    // Регистрация (register)
    "register.title": "Регистрация",
    "register.subtitle": "Создайте новую учетную запись",
    "register.systemDescription": "Система технической поддержки",
    "register.personalInfo": "Личная информация",
    "register.personalInfoDesc": "Основные данные о вас",
    "register.workInfo": "Рабочая информация",
    "register.workInfoDesc": "Информация о работе",
    "register.security": "Безопасность",
    "register.securityDesc": "Настройки безопасности",
    "register.firstName": "Имя",
    "register.lastName": "Фамилия",
    "register.middleName": "Отчество",
    "register.email": "Email",
    "register.phone": "Телефон",
    "register.birthDate": "Дата рождения",
    "register.department": "Отдел",
    "register.position": "Должность",
    "register.employeeId": "ID сотрудника",
    "register.manager": "Руководитель",
    "register.workLocation": "Место работы",
    "register.startDate": "Дата начала работы",
    "register.password": "Пароль",
    "register.confirmPassword": "Подтвердите пароль",
    "register.securityQuestion": "Секретный вопрос",
    "register.securityAnswer": "Ответ на секретный вопрос",
    "register.additionalInfo": "Дополнительная информация",
    "register.agreeToTerms": "Согласен с условиями использования",
    "register.selectDepartment": "Выберите отдел",
    "register.selectSecurityQuestion": "Выберите секретный вопрос",
    "register.submitting": "Отправка...",
    "register.complete": "Завершить",
    "register.completed": "Регистрация завершена",
    "register.requestSent": "Запрос отправлен",
    "register.thankYou": "Спасибо за регистрацию!",
    "register.requestReview": "Ваш запрос будет рассмотрен администратором",
    "register.backToLogin": "Вернуться к входу",
    "register.alreadyHaveAccount": "Уже есть аккаунт?",
    "register.login": "Войти",

    // Аналитика (analytics)
    "analytics.last7Days": "Последние 7 дней",
    "analytics.last30Days": "Последние 30 дней",
    "analytics.last90Days": "Последние 90 дней",
    "analytics.lastYear": "Последний год",
    "analytics.exportToExcel": "Экспорт в Excel",
    "analytics.exporting": "Экспорт...",
    "analytics.totalTickets": "Всего заявок",
    "analytics.activeUsers": "Активные пользователи",
    "analytics.avgResolutionTime": "Среднее время решения",
    "analytics.teamEfficiency": "Эффективность команды",
    "analytics.statusDistribution": "Распределение по статусам",
    "analytics.priorityDistribution": "Распределение по приоритетам",
    "analytics.popularCategories": "Популярные категории",
    "analytics.recentActivity": "Последняя активность",
    "analytics.publish": "Опубликованных",
    "analytics.views": "Просмотров",
    "analytics.helpful": "Полезных",
    "analytics.notHelpful": "Не полезных",

    // Пользователи (users)
    "users.title": "Управление пользователями",
    "users.subtitle": "Управление учетными записями пользователей",
    "users.addUser": "Добавить пользователя",
    "users.activeUsers": "Активные пользователи",
    "users.pendingUsers": "Ожидающие одобрения",
    "users.firstName": "Имя",
    "users.lastName": "Фамилия",
    "users.email": "Email",
    "users.phone": "Телефон",
    "users.role": "Роль",
    "users.department": "Отдел",
    "users.status": "Статус",
    "users.lastLogin": "Последний вход",
    "users.actions": "Действия",
    "users.editUser": "Редактировать пользователя",
    "users.noUsers": "Пользователи не найдены",
    "users.noPendingUsers": "Нет пользователей, ожидающих одобрения",
    "users.approve": "Одобрить",
    "users.reject": "Отклонить",

    // Мои заявки (myTickets)
    "myTickets.title": "Мои заявки",
    "myTickets.subtitle": "Просмотр и отслеживание ваших заявок",
    "myTickets.createTicket": "Создать заявку",
    "myTickets.filters": "Фильтры",
    "myTickets.searchPlaceholder": "Поиск заявок...",
    "myTickets.statusFilter": "Фильтр по статусу",
    "myTickets.allStatuses": "Все статусы",
    "myTickets.created": "Создано",
    "myTickets.updated": "Обновлено",
    "myTickets.assignedTo": "Назначено",
    "myTickets.view": "Просмотр",
    "myTickets.noTickets": "У вас нет заявок",
    "myTickets.createFirstTicket": "Создать первую заявку",

    // Отделы (departments)
    "departments.it": "IT отдел",
    "departments.sales": "Отдел продаж",
    "departments.purchasing": "Отдел закупок",
    "departments.support": "Служба поддержки",
    "departments.accounting": "Бухгалтерия",
    "departments.hr": "Отдел кадров",
    "departments.marketing": "Маркетинг",
    "departments.legal": "Юридический отдел",
    "departments.production": "Производство",
    "departments.logistics": "Логистика",

    // Секретные вопросы (securityQuestions)
    "securityQuestions.pet": "Как звали вашего первого питомца?",
    "securityQuestions.city": "В каком городе вы родились?",
    "securityQuestions.friend": "Как звали вашего лучшего друга детства?",
    "securityQuestions.car": "Какая была ваша первая машина?",
    "securityQuestions.school": "Как называлась ваша школа?",

    // Валидация (validation)
    "validation.firstNameRequired": "Имя обязательно",
    "validation.lastNameRequired": "Фамилия обязательна",
    "validation.emailRequired": "Email обязателен",
    "validation.phoneRequired": "Телефон обязателен",
    "validation.invalidEmail": "Неверный формат email",
    "validation.emailExists": "Пользователь с таким email уже существует",
    "validation.departmentRequired": "Отдел обязателен",
    "validation.positionRequired": "Должность обязательна",
    "validation.employeeIdRequired": "ID сотрудника обязателен",
    "validation.workLocationRequired": "Место работы обязательно",
    "validation.passwordRequired": "Пароль обязателен",
    "validation.passwordLength": "Пароль должен содержать минимум 8 символов",
    "validation.passwordsNotMatch": "Пароли не совпадают",
    "validation.securityQuestionRequired": "Секретный вопрос обязателен",
    "validation.securityAnswerRequired": "Ответ на секретный вопрос обязателен",
    "validation.termsRequired": "Необходимо согласиться с условиями",

    // Сообщения (messages)
    "messages.error": "Произошла ошибка",
    "messages.success": "Операция выполнена успешно",
    "messages.deleteConfirm": "Вы уверены, что хотите удалить?",
    "messages.exportError": "Ошибка при экспорте данных",
  },
  en: {
    // Navigation
    "nav.home": "Home",
    "nav.tickets": "Tickets",
    "nav.myTickets": "My Tickets",
    "nav.knowledgeBase": "Knowledge Base",
    "nav.users": "Users",
    "nav.analytics": "Analytics",
    "nav.logout": "Logout",

    // Home page
    "home.greeting.morning": "Good morning",
    "home.greeting.afternoon": "Good afternoon",
    "home.greeting.evening": "Good evening",
    "home.welcome": "Welcome to the technical support system",
    "home.myRequests": "My requests",
    "home.inProgress": "In progress",
    "home.resolved": "Resolved",
    "home.averageTime": "Average time",
    "home.myTickets": "My tickets",
    "home.newTickets": "New tickets",
    "home.resolvedToday": "Resolved today",
    "home.totalTickets": "Total tickets",
    "home.totalUsers": "Users",
    "home.kbArticles": "KB articles",
    "home.activeTickets": "Active tickets",
    "home.quickActions": "Quick actions",
    "home.recentUpdates": "Recent updates",
    "home.createTicket": "Create ticket",
    "home.createTicketDesc": "Report a problem or request help",
    "home.myTicketsDesc": "View the status of your tickets",
    "home.knowledgeBaseDesc": "Find answers to frequently asked questions",
    "home.manageTickets": "Manage tickets",
    "home.manageTicketsDesc": "View and process tickets",
    "home.manageKB": "Knowledge base",
    "home.manageKBDesc": "View and edit articles",
    "home.createArticle": "Create article",
    "home.createArticleDesc": "Add a new article to KB",
    "home.manageUsers": "User management",
    "home.manageUsersDesc": "Manage user accounts",
    "home.analyticsDesc": "View reports and statistics",
    "home.systemUpdated": "System updated",
    "home.systemUpdatedDesc": "Added new ticket management features",
    "home.kbUpdated": "Knowledge base updated",
    "home.kbUpdatedDesc": "Added new security articles",
    "home.maintenance": "Scheduled maintenance",
    "home.maintenanceDesc": "Scheduled for the weekend",

    // Tickets
    "tickets.title": "Ticket Management",
    "tickets.subtitle": "Processing and assigning technical support tickets",
    "tickets.createTicket": "Create Ticket",
    "tickets.searchPlaceholder": "Search tickets...",
    "tickets.sortNewest": "Newest first",
    "tickets.sortOldest": "Oldest first",
    "tickets.sortPriority": "By priority",
    "tickets.sortStatus": "By status",
    "tickets.allTickets": "All",
    "tickets.openTickets": "Open",
    "tickets.inProgressTickets": "In Progress",
    "tickets.resolvedTickets": "Resolved",
    "tickets.closedTickets": "Closed",
    "tickets.assignedTo": "Assigned to:",
    "tickets.noTickets": "No tickets found matching the criteria.",
    "tickets.takeTicket": "Take Ticket",
    "tickets.newTicketTitle": "Create New Ticket",
    "tickets.newTicketSubtitle": "Describe your problem or request",
    "tickets.backToTickets": "Back to tickets",
    "tickets.ticketInfo": "Ticket Information",
    "tickets.ticketTitle": "Ticket Title",
    "tickets.ticketTitlePlaceholder": "Briefly describe the problem",
    "tickets.description": "Problem Description",
    "tickets.descriptionPlaceholder": "Describe the problem in detail, steps to reproduce, expected result",
    "tickets.category": "Category",
    "tickets.selectCategory": "Select category",
    "tickets.priority": "Priority",
    "tickets.contactInfo": "Contact Information",
    "tickets.name": "Name",
    "tickets.email": "Email",
    "tickets.phone": "Phone",
    "tickets.creating": "Creating...",

    // Ticket categories
    "category.technical": "Technical Support",
    "category.account": "Account Issues",
    "category.billing": "Billing Questions",
    "category.feature": "Feature Request",
    "category.other": "Other",

    // Knowledge Base
    "kb.title": "Knowledge Base",
    "kb.subtitle": "Find answers to frequently asked questions and instructions",
    "kb.createArticle": "Create Article",
    "kb.searchPlaceholder": "Search knowledge base...",
    "kb.allCategories": "All categories",
    "kb.sortNewest": "Newest first",
    "kb.sortOldest": "Oldest first",
    "kb.sortMostViewed": "Most viewed",
    "kb.sortMostHelpful": "Most helpful",
    "kb.views": "views",
    "kb.author": "Author:",
    "kb.readArticle": "Read article",
    "kb.noArticles": "No articles found for your query.",
    "kb.editorTitle": "Knowledge Base Editor",
    "kb.backToKB": "Back to knowledge base",
    "kb.saveDraft": "Save Draft",
    "kb.publish": "Publish",
    "kb.publishing": "Publishing...",
    "kb.editing": "Editing",
    "kb.preview": "Preview",
    "kb.articleTitle": "Article Title",
    "kb.articleTitlePlaceholder": "Enter article title",
    "kb.formatPanel": "Formatting Panel",
    "kb.content": "Article Content",
    "kb.contentPlaceholder": "Enter article content (Markdown supported)",
    "kb.markdownSupport": "Markdown supported:",
    "kb.bold": "Bold",
    "kb.italic": "Italic",
    "kb.heading": "Heading",
    "kb.link": "Link",
    "kb.code": "Code",
    "kb.list": "List",
    "kb.selectCategory": "Select category",
    "kb.tags": "Tags",
    "kb.publishSettings": "Publication Settings",
    "kb.recommended": "Recommended article",
    "kb.allowComments": "Allow comments",
    "kb.articlePublished": "Article successfully published!",
    "kb.articlePublishedDesc": "has been successfully added to the knowledge base.",
    "kb.toKnowledgeBase": "To knowledge base",
    "kb.createAnother": "Create another",

    // Analytics
    "analytics.title": "Advanced Analytics",
    "analytics.subtitle": "Detailed reports and statistics on support service performance",
    "analytics.last7days": "Last 7 days",
    "analytics.last30days": "Last 30 days",
    "analytics.last90days": "Last 90 days",
    "analytics.lastYear": "Last year",
    "analytics.exportExcel": "Export Excel",
    "analytics.exporting": "Exporting...",
    "analytics.print": "Print",
    "analytics.totalTickets": "Total requests",
    "analytics.activeUsers": "Active users",
    "analytics.avgResolutionTime": "Average resolution time",
    "analytics.teamEfficiency": "Team efficiency",
    "analytics.requiresAttention": "Requires attention",
    "analytics.usersAwaitingApproval": "users awaiting registration approval",
    "analytics.goToManagement": "Go to management",
    "analytics.activityDynamics": "Ticket dynamics (last 7 days)",
    "analytics.created": "Created:",
    "analytics.resolved": "Resolved:",
    "analytics.statusDistribution": "Status distribution",
    "analytics.popularCategories": "Popular categories",
    "analytics.priorityDistribution": "Priority distribution",
    "analytics.recentActivity": "Recent activity",
    "analytics.teamEfficiencyTable": "Support team efficiency",
    "analytics.employee": "Employee",
    "analytics.assigned": "Assigned",
    "analytics.resolved": "Resolved",
    "analytics.efficiency": "Efficiency",
    "analytics.avgTime": "Average time",
    "analytics.kbStats": "Knowledge base statistics",
    "analytics.publishedArticles": "Published articles",
    "analytics.totalViews": "Total views",
    "analytics.helpfulRatings": "Helpful ratings",
    "analytics.helpfulnessRating": "Helpfulness rating",

    // Common
    "common.loading": "Loading...",
    "common.save": "Save",
    "common.cancel": "Cancel",
    "common.delete": "Delete",
    "common.edit": "Edit",
    "common.create": "Create",
    "common.search": "Search",
    "common.filter": "Filter",
    "common.all": "All",
    "common.active": "Active",
    "common.inactive": "Inactive",
    "common.yes": "Yes",
    "common.no": "No",
    "common.back": "Back",
    "common.next": "Next",
    "common.submit": "Submit",
    "common.close": "Close",

    // Roles
    "role.admin": "Administrator",
    "role.support": "Support Staff",
    "role.client": "Client",

    // Ticket statuses
    "status.new": "New",
    "status.in-progress": "In Progress",
    "status.resolved": "Resolved",
    "status.closed": "Closed",

    // Priorities
    "priority.low": "Low",
    "priority.medium": "Medium",
    "priority.high": "High",
    "priority.urgent": "Urgent",

    // Authentication
    "auth.login": "Login",
    "auth.register": "Register",
    "auth.email": "Email",
    "auth.password": "Password",
    "auth.confirmPassword": "Confirm Password",
    "auth.firstName": "First Name",
    "auth.lastName": "Last Name",
    "auth.loginButton": "Sign In",
    "auth.registerButton": "Sign Up",
    "auth.switchToRegister": "Don't have an account? Sign up",
    "auth.switchToLogin": "Already have an account? Sign in",

    // Notifications
    "notifications.title": "Notifications",
    "notifications.markAsRead": "Mark as read",
    "notifications.markAllAsRead": "Mark all as read",
    "notifications.noNotifications": "No notifications",
    "notifications.newTicket": "New ticket created",
    "notifications.ticketAssigned": "Ticket assigned to you",
    "notifications.ticketUpdated": "Ticket updated",
    "notifications.ticketResolved": "Ticket resolved",

    // Time
    "time.hoursAgo": "hours ago",
    "time.daysAgo": "days ago",
    "time.today": "today",
    "time.yesterday": "yesterday",

    // Login
    "login.title": "Sign In",
    "login.subtitle": "Sign in to your account",
    "login.systemDescription": "Technical Support System",
    "login.email": "Email",
    "login.password": "Password",
    "login.emailPlaceholder": "Enter your email",
    "login.passwordPlaceholder": "Enter your password",
    "login.login": "Sign In",
    "login.loggingIn": "Signing in...",
    "login.testAccounts": "Test Accounts",
    "login.noAccount": "Don't have an account?",
    "login.register": "Sign Up",
    "login.invalidCredentials": "Invalid credentials",

    // Register
    "register.title": "Sign Up",
    "register.subtitle": "Create a new account",
    "register.systemDescription": "Technical Support System",
    "register.personalInfo": "Personal Information",
    "register.personalInfoDesc": "Basic information about you",
    "register.workInfo": "Work Information",
    "register.workInfoDesc": "Information about your work",
    "register.security": "Security",
    "register.securityDesc": "Security settings",
    "register.firstName": "First Name",
    "register.lastName": "Last Name",
    "register.middleName": "Middle Name",
    "register.email": "Email",
    "register.phone": "Phone",
    "register.birthDate": "Birth Date",
    "register.department": "Department",
    "register.position": "Position",
    "register.employeeId": "Employee ID",
    "register.manager": "Manager",
    "register.workLocation": "Work Location",
    "register.startDate": "Start Date",
    "register.password": "Password",
    "register.confirmPassword": "Confirm Password",
    "register.securityQuestion": "Security Question",
    "register.securityAnswer": "Security Answer",
    "register.additionalInfo": "Additional Information",
    "register.agreeToTerms": "I agree to the terms of use",
    "register.selectDepartment": "Select department",
    "register.selectSecurityQuestion": "Select security question",
    "register.submitting": "Submitting...",
    "register.complete": "Complete",
    "register.completed": "Registration Completed",
    "register.requestSent": "Request Sent",
    "register.thankYou": "Thank you for registering!",
    "register.requestReview": "Your request will be reviewed by an administrator",
    "register.backToLogin": "Back to Login",
    "register.alreadyHaveAccount": "Already have an account?",
    "register.login": "Sign In",

    // Analytics
    "analytics.last7Days": "Last 7 Days",
    "analytics.last30Days": "Last 30 Days",
    "analytics.last90Days": "Last 90 Days",
    "analytics.lastYear": "Last Year",
    "analytics.exportToExcel": "Export to Excel",
    "analytics.exporting": "Exporting...",
    "analytics.totalTickets": "Total Tickets",
    "analytics.activeUsers": "Active Users",
    "analytics.avgResolutionTime": "Avg Resolution Time",
    "analytics.teamEfficiency": "Team Efficiency",
    "analytics.statusDistribution": "Status Distribution",
    "analytics.priorityDistribution": "Priority Distribution",
    "analytics.popularCategories": "Popular Categories",
    "analytics.recentActivity": "Recent Activity",
    "analytics.publish": "Published",
    "analytics.views": "Views",
    "analytics.helpful": "Helpful",
    "analytics.notHelpful": "Not Helpful",

    // Users
    "users.title": "User Management",
    "users.subtitle": "Manage user accounts",
    "users.addUser": "Add User",
    "users.activeUsers": "Active Users",
    "users.pendingUsers": "Pending Approval",
    "users.firstName": "First Name",
    "users.lastName": "Last Name",
    "users.email": "Email",
    "users.phone": "Phone",
    "users.role": "Role",
    "users.department": "Department",
    "users.status": "Status",
    "users.lastLogin": "Last Login",
    "users.actions": "Actions",
    "users.editUser": "Edit User",
    "users.noUsers": "No users found",
    "users.noPendingUsers": "No users pending approval",
    "users.approve": "Approve",
    "users.reject": "Reject",

    // My Tickets
    "myTickets.title": "My Tickets",
    "myTickets.subtitle": "View and track your tickets",
    "myTickets.createTicket": "Create Ticket",
    "myTickets.filters": "Filters",
    "myTickets.searchPlaceholder": "Search tickets...",
    "myTickets.statusFilter": "Status Filter",
    "myTickets.allStatuses": "All Statuses",
    "myTickets.created": "Created",
    "myTickets.updated": "Updated",
    "myTickets.assignedTo": "Assigned to",
    "myTickets.view": "View",
    "myTickets.noTickets": "You have no tickets",
    "myTickets.createFirstTicket": "Create your first ticket",

    // Departments
    "departments.it": "IT Department",
    "departments.sales": "Sales Department",
    "departments.purchasing": "Purchasing Department",
    "departments.support": "Support Department",
    "departments.accounting": "Accounting Department",
    "departments.hr": "HR Department",
    "departments.marketing": "Marketing Department",
    "departments.legal": "Legal Department",
    "departments.production": "Production Department",
    "departments.logistics": "Logistics Department",

    // Security Questions
    "securityQuestions.pet": "What was the name of your first pet?",
    "securityQuestions.city": "What city were you born in?",
    "securityQuestions.friend": "What was the name of your childhood best friend?",
    "securityQuestions.car": "What was your first car?",
    "securityQuestions.school": "What was the name of your school?",

    // Validation
    "validation.firstNameRequired": "First name is required",
    "validation.lastNameRequired": "Last name is required",
    "validation.emailRequired": "Email is required",
    "validation.phoneRequired": "Phone is required",
    "validation.invalidEmail": "Invalid email format",
    "validation.emailExists": "User with this email already exists",
    "validation.departmentRequired": "Department is required",
    "validation.positionRequired": "Position is required",
    "validation.employeeIdRequired": "Employee ID is required",
    "validation.workLocationRequired": "Work location is required",
    "validation.passwordRequired": "Password is required",
    "validation.passwordLength": "Password must be at least 8 characters",
    "validation.passwordsNotMatch": "Passwords do not match",
    "validation.securityQuestionRequired": "Security question is required",
    "validation.securityAnswerRequired": "Security answer is required",
    "validation.termsRequired": "You must agree to the terms",

    // Messages
    "messages.error": "An error occurred",
    "messages.success": "Operation completed successfully",
    "messages.deleteConfirm": "Are you sure you want to delete?",
    "messages.exportError": "Error exporting data",
  },
}

const LanguageProvider = ({ children }: { children: ReactNode }) => {
  const [language, setLanguage] = useState<"ru" | "en">("ru")

  useEffect(() => {
    // При загрузке компонента пытаемся получить язык из localStorage
    const storedLanguage = localStorage.getItem("language") as "ru" | "en" | null
    if (storedLanguage) {
      setLanguage(storedLanguage)
    }
  }, [])

  useEffect(() => {
    // При изменении языка сохраняем его в localStorage
    localStorage.setItem("language", language)
  }, [language])

  const t = (key: string): string => {
    const translation = translations[language]?.[key] || translations["ru"]?.[key] || key
    return translation
  }

  return <LanguageContext.Provider value={{ language, setLanguage, t }}>{children}</LanguageContext.Provider>
}

const useLanguage = (): LanguageContextType => {
  const context = useContext(LanguageContext)
  if (context === undefined) {
    throw new Error("useLanguage must be used within a LanguageProvider")
  }
  return context
}

export { LanguageProvider, useLanguage }
